=== chharvey/extrajs-geo/state-data.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "http://chharvey.github.io/extrajs-geo/state-data.schema.json",
  "type": "array",
  "items": {
    "type": "object",
    "description": "data for a US state or territory",
    "required": ["code", "name", "population", "area", "region"],
    "additionalProperties": false,
    "properties": {
      "code"      : { "type": "string" , "description": "the postal code of the state/territory" },
      "name"      : { "type": "string" , "description": "the common name of the state/territory" },
      "population": { "type": "integer", "description": "the number of residents of the state/territory, according to the latest census" },
      "area"      : { "type": "number" , "description": "the area of state/territory land, in square kilometers (sq. km)" },
      "region"    : {
        "enum": ["northeast", "south", "midwest", "southwest", "west"],
        "description": "the region(s) of the US to which this state/territory belongs. see <https://en.wikipedia.org/wiki/List_of_regions_of_the_United_States>."
      }
    }
  }
}

=== chharvey/extrajs-geo/state-data.json
[
  { "code": "AL",  "name": "Alabama"       ,  "population":  4779736,  "area":  52419, "region": "south"     },
  { "code": "AK",  "name": "Alaska"        ,  "population":   710231,  "area": 663267, "region": "west"      },
  { "code": "AZ",  "name": "Arizona"       ,  "population":  6392017,  "area": 113998, "region": "southwest" },
  { "code": "AR",  "name": "Arkansas"      ,  "population":  2915918,  "area":  53179, "region": "south"     },
  { "code": "CA",  "name": "California"    ,  "population": 37253956,  "area": 163696, "region": "west"      },
  { "code": "CO",  "name": "Colorado"      ,  "population":  5029196,  "area": 104094, "region": "west"      },
  { "code": "CT",  "name": "Connecticut"   ,  "population":  3574097,  "area":   5543, "region": "northeast" },
  { "code": "DE",  "name": "Delaware"      ,  "population":   897934,  "area":   2489, "region": "northeast" },
  { "code": "FL",  "name": "Florida"       ,  "population": 18801310,  "area":  65755, "region": "south"     },
  { "code": "GA",  "name": "Georgia"       ,  "population":  9687653,  "area":  59425, "region": "south"     },
  { "code": "HI",  "name": "Hawaii"        ,  "population":  1360301,  "area":  10931, "region": "west"      },
  { "code": "ID",  "name": "Idaho"         ,  "population":  1567582,  "area":  83570, "region": "west"      },
  { "code": "IL",  "name": "Illinois"      ,  "population": 12830632,  "area":  57914, "region": "midwest"   },
  { "code": "IN",  "name": "Indiana"       ,  "population":  6483802,  "area":  36418, "region": "midwest"   },
  { "code": "IA",  "name": "Iowa"          ,  "population":  3046355,  "area":  56272, "region": "midwest"   },
  { "code": "KS",  "name": "Kansas"        ,  "population":  2853118,  "area":  82277, "region": "midwest"   },
  { "code": "KY",  "name": "Kentucky"      ,  "population":  4339367,  "area":  40409, "region": "south"     },
  { "code": "LA",  "name": "Louisiana"     ,  "population":  4533372,  "area":  51840, "region": "south"     },
  { "code": "ME",  "name": "Maine"         ,  "population":  1328361,  "area":  35385, "region": "northeast" },
  { "code": "MD",  "name": "Maryland"      ,  "population":  5773552,  "area":  12407, "region": "northeast" },
  { "code": "MA",  "name": "Massachusetts" ,  "population":  6547629,  "area":  10555, "region": "northeast" },
  { "code": "MI",  "name": "Michigan"      ,  "population":  9883640,  "area":  96716, "region": "midwest"   },
  { "code": "MN",  "name": "Minnesota"     ,  "population":  5303925,  "area":  86939, "region": "midwest"   },
  { "code": "MS",  "name": "Mississippi"   ,  "population":  2967297,  "area":  48430, "region": "south"     },
  { "code": "MO",  "name": "Missouri"      ,  "population":  5988927,  "area":  69704, "region": "midwest"   },
  { "code": "MT",  "name": "Montana"       ,  "population":   989415,  "area": 147042, "region": "west"      },
  { "code": "NE",  "name": "Nebraska"      ,  "population":  1826341,  "area":  77354, "region": "midwest"   },
  { "code": "NV",  "name": "Nevada"        ,  "population":  2700551,  "area": 110561, "region": "west"      },
  { "code": "NH",  "name": "New Hampshire" ,  "population":  1316470,  "area":   9350, "region": "northeast" },
  { "code": "NJ",  "name": "New Jersey"    ,  "population":  8791894,  "area":   8721, "region": "northeast" },
  { "code": "NM",  "name": "New Mexico"    ,  "population":  2059179,  "area": 121589, "region": "southwest" },
  { "code": "NY",  "name": "New York"      ,  "population": 19378102,  "area":  54556, "region": "northeast" },
  { "code": "NC",  "name": "North Carolina",  "population":  9535483,  "area":  53819, "region": "south"     },
  { "code": "ND",  "name": "North Dakota"  ,  "population":   672591,  "area":  70700, "region": "midwest"   },
  { "code": "OH",  "name": "Ohio"          ,  "population": 11536504,  "area":  44825, "region": "midwest"   },
  { "code": "OK",  "name": "Oklahoma"      ,  "population":  3751351,  "area":  69898, "region": "southwest" },
  { "code": "OR",  "name": "Oregon"        ,  "population":  3831074,  "area":  98381, "region": "west"      },
  { "code": "PA",  "name": "Pennsylvania"  ,  "population": 12702379,  "area":  46055, "region": "northeast" },
  { "code": "RI",  "name": "Rhode Island"  ,  "population":  1052567,  "area":   1545, "region": "northeast" },
  { "code": "SC",  "name": "South Carolina",  "population":  4625364,  "area":  32020, "region": "south"     },
  { "code": "SD",  "name": "South Dakota"  ,  "population":   814180,  "area":  77117, "region": "midwest"   },
  { "code": "TN",  "name": "Tennessee"     ,  "population":  6346105,  "area":  42143, "region": "south"     },
  { "code": "TX",  "name": "Texas"         ,  "population": 25145561,  "area": 268581, "region": "southwest" },
  { "code": "UT",  "name": "Utah"          ,  "population":  2763885,  "area":  84899, "region": "west"      },
  { "code": "VT",  "name": "Vermont"       ,  "population":   625741,  "area":   9614, "region": "northeast" },
  { "code": "VA",  "name": "Virginia"      ,  "population":  8260405,  "area":  42774, "region": "south"     },
  { "code": "WA",  "name": "Washington"    ,  "population":  6971406,  "area":  71300, "region": "west"      },
  { "code": "WV",  "name": "West Virginia" ,  "population":  1854304,  "area":  24230, "region": "south"     },
  { "code": "WI",  "name": "Wisconsin"     ,  "population":  5686986,  "area":  65498, "region": "midwest"   },
  { "code": "WY",  "name": "Wyoming"       ,  "population":   563626,  "area":  97814, "region": "west"      }
]
